'use client'
import { useMemo, useState } from 'react'
import type { LaunchLane } from '@/lib/problems'
import { LaunchLog, type LaunchRecord } from './LaunchLog'
const clamp=(n:number,min:number,max:number)=>Math.max(min,Math.min(max,n))
export function LaunchCourse({ lanes, length, maxStretch, onSolved }: { lanes: LaunchLane[]; length: number; maxStretch: number; onSolved:()=>void }) {
 const [stretches,setStretches]=useState<Record<string,number>>({}); const [records,setRecords]=useState<Record<string,LaunchRecord[]>>({}); const [selected,setSelected]=useState(lanes[0].id); const [dragging,setDragging]=useState(false)
 const current=stretches[selected]??0; const scale=278/length
 const setStretch=(e:React.PointerEvent<SVGSVGElement>)=>{const rect=e.currentTarget.getBoundingClientRect(); const dx=(e.clientX-rect.left)/rect.width*360; setStretches(s=>({...s,[selected]:clamp(Math.round((70-dx)/5),0,maxStretch)}))}
 const fire=(id=selected)=>{const stretch=stretches[id]??0; const distance=4*stretch*stretch; const lane=lanes.find(l=>l.id===id)!; setRecords(r=>({...r,[id]:[...(r[id]??[]),{stretch,distance}]})); if(Math.abs(distance-lane.goalCenterCm)<=lane.goalToleranceCm) { const next=lanes.every(l=>{const rs=records[l.id]??[]; return l.id===id ? Math.abs(distance-l.goalCenterCm)<=l.goalToleranceCm : rs.some(x=>Math.abs(x.distance-l.goalCenterCm)<=l.goalToleranceCm)}); if(next) setTimeout(onSolved,400) } }
 const all=useMemo(()=>lanes.flatMap(l=>records[l.id]??[]),[lanes,records])
 return <div className="flex flex-col gap-3"><svg viewBox={`0 0 ${360} ${lanes.length===1?110:200}`} className="w-full" style={{touchAction:'none'}} onPointerMove={e=>dragging&&setStretch(e)} onPointerUp={()=>{setDragging(false);fire()}}>{lanes.map((lane,i)=>{const y=i*90+20; const stretch=stretches[lane.id]??0; const x=70-stretch*5; const goalX=70+lane.goalCenterCm*scale; return <g key={lane.id} onPointerDown={()=>setSelected(lane.id)}><text x="8" y={y} fontSize="11" fontWeight="bold">{lane.label}</text><line x1="70" y1={y+42} x2="348" y2={y+42} stroke="#B9A88A" strokeWidth="3"/><rect x={goalX-lane.goalToleranceCm*scale} y={y+18} width={lane.goalToleranceCm*2*scale} height="48" fill="#5FB85F" opacity=".3"/><text x={goalX} y={y+15} textAnchor="middle" fontSize="12">🏁 {lane.goalCenterCm}cm</text><line x1="70" y1={y+10} x2="70" y2={y+42} stroke="#7A6A52" strokeWidth="5"/><line x1="70" y1={y+10} x2={x+17} y2={y+10} stroke="#D9534F" strokeWidth="2"/><line x1="70" y1={y+10} x2={x+17} y2={y+20} stroke="#E8B33A" strokeWidth="2"/><g onPointerDown={e=>{e.stopPropagation();setSelected(lane.id);setDragging(true)}}><rect x={x} y={y-1} width="34" height="22" rx="6" fill="#FF9040"/><circle cx={x+8} cy={y+22} r="4" fill="#3D3A38"/><circle cx={x+27} cy={y+22} r="4" fill="#3D3A38"/><circle cx={x+17} cy={y+10} r="28" fill="transparent"/></g></g>})}</svg><div className="flex items-center justify-between rounded-xl bg-accent/40 px-4 py-3"><span>のばした 長さ</span><strong className="text-2xl">{current}cm</strong></div><div className="flex gap-3"><button onClick={()=>fire()} className="min-h-12 flex-1 rounded-xl bg-primary px-4 font-bold text-primary-foreground">🚀 はなす</button><button onClick={()=>setStretches(s=>({...s,[selected]:0}))} className="min-h-12 rounded-xl border border-border px-4 font-bold">↩ もどす</button></div><LaunchLog records={all} courseLength={length}/></div>
}
