export type Weight = { id: string; grams: number; position: number; movable: boolean; gramsEditable: boolean }
export type RealWorldVisual = 'seesaw' | 'nail-puller' | 'scale' | 'slingshot' | 'archery'
export type BalanceProblem = { id: string; archetype: 'balance'; title: string; emoji: string; difficultyLabel: 'かんたん' | 'ふつう' | 'やってみる'; prompt: string; notches: number; weights: Weight[]; gramsRange?: { min: number; max: number; step: number }; solved: { discovery: string; formula: string; realWorldTitle: string; realWorldBody: string; realWorldVisual: RealWorldVisual; note?: string } }
export type LaunchLane = { id: string; label: string; targetStretchRange: [number, number] }
export type LaunchProblem = { id: string; archetype: 'launch'; title: string; emoji: string; difficultyLabel: 'かんたん' | 'ふつう' | 'やってみる'; grade: 3; subject: 'science'; curriculum: { code: string; unit: string }; prompt: string; courseLengthCm: number; maxStretchCm: number; lanes: LaunchLane[]; solved: { discovery: string; formula: string; realWorldTitle: string; realWorldBody: string; realWorldVisual: RealWorldVisual; note?: string } }
export type Problem = BalanceProblem | LaunchProblem

const balanceProblems: BalanceProblem[] = [
 { id: 'lever-01', archetype: 'balance', title: 'つり合いを 見つけよう', emoji: '⚖️', difficultyLabel: 'かんたん', prompt: '右の重りを動かして、てこを水平にしよう。', notches: 6, weights: [{ id: 'left', grams: 10, position: -3, movable: false, gramsEditable: false }, { id: 'right', grams: 10, position: 6, movable: true, gramsEditable: false }], solved: { discovery: '同じ重さなら、支点から同じ距離につり合う', formula: '10g × 3 = 10g × 3', realWorldTitle: 'シーソー', realWorldBody: 'シーソーも、左右の重さと支点からの距離でつり合いが決まるよ。', realWorldVisual: 'seesaw' } },
 { id: 'lever-02', archetype: 'balance', title: '重さが ちがうとき', emoji: '🪨', difficultyLabel: 'ふつう', prompt: '重い右の重りを、どこに置くと水平になるかな？', notches: 6, weights: [{ id: 'left', grams: 10, position: -6, movable: false, gramsEditable: false }, { id: 'right', grams: 20, position: 6, movable: true, gramsEditable: false }], solved: { discovery: '重いほうを、支点に近づける', formula: '10g × 6 = 20g × 3', realWorldTitle: 'くぎ抜き', realWorldBody: 'くぎ抜きは、長いほうを持つと、小さな力でもくぎを抜きやすくなるよ。', realWorldVisual: 'nail-puller' } },
 { id: 'lever-03', archetype: 'balance', title: '答えは ひとつじゃない', emoji: '🧩', difficultyLabel: 'やってみる', prompt: '重さや場所を変えて、水平になる組み合わせを見つけよう。', notches: 6, weights: [{ id: 'left', grams: 15, position: -4, movable: false, gramsEditable: true }, { id: 'right', grams: 5, position: 6, movable: true, gramsEditable: true }], gramsRange: { min: 5, max: 30, step: 5 }, solved: { discovery: 'つり合うやり方は、ひとつじゃない', formula: '15g × 4 = 20g × 3（例）', realWorldTitle: 'はかり', realWorldBody: 'はかりは、ものの重さを比べるために、てこのつり合いを使っているよ。', realWorldVisual: 'scale' } },
]
const launchProblems: LaunchProblem[] = [
 { id: 'rubber-01', archetype: 'launch', title: 'ゴムの力 ①', emoji: '🚗', difficultyLabel: 'かんたん', grade: 3, subject: 'science', curriculum: { code: '理科 3年 A(2)', unit: '風とゴムの力の働き' }, prompt: '車を後ろに引っ張って離そう。ゴールのところで止められるかな？', courseLengthCm: 950, maxStretchCm: 15, lanes: [{ id: 'a', label: 'コース', targetStretchRange: [6, 13] }], solved: { discovery: 'ゴムを長く伸ばすほど、車は遠くまで進む', formula: '伸ばした長さと進んだ距離を確かめよう', realWorldTitle: 'これ、どこで使われてる？', realWorldBody: 'パチンコ、ゴム鉄砲、ボウガン、それから車のサスペンション。ぜんぶ「もとに戻ろうとする力」を使っているよ。', realWorldVisual: 'slingshot' } },
 { id: 'rubber-02', archetype: 'launch', title: 'ゴムの力 ②', emoji: '🏁', difficultyLabel: 'ふつう', grade: 3, subject: 'science', curriculum: { code: '理科 3年 A(2)', unit: '風とゴムの力の働き' }, prompt: '今度はゴールが2つ。近いゴールと遠いゴール、両方止めてみよう。', courseLengthCm: 950, maxStretchCm: 15, lanes: [{ id: 'a', label: '近いゴール', targetStretchRange: [3, 6] }, { id: 'b', label: '遠いゴール', targetStretchRange: [10, 14] }], solved: { discovery: '近いゴールは短く、遠いゴールは長く伸ばす', formula: '伸ばした長さと進んだ距離を確かめよう', realWorldTitle: 'これ、どこで使われてる？', realWorldBody: '距離をねらって飛ばすものは、ぜんぶこの考え方。アーチェリー、水鉄砲、それから消防車のホース。', realWorldVisual: 'archery', note: '記録を縦に並べて見てみよう。伸ばした長さと進んだ距離に、決まりが見えるよ' } },
]
export const problems: Problem[] = [...balanceProblems, ...launchProblems]
export function getProblem(id: string) { return problems.find((p) => p.id === id) }
export function getNextProblem(id: string) { const index = problems.findIndex((p) => p.id === id); return problems[(index + 1) % problems.length] }
export function isLaunchProblem(problem: Problem): problem is LaunchProblem { return problem.archetype === 'launch' }
