export type Weight = { id: string; grams: number; position: number; movable: boolean; gramsEditable: boolean }
export type BalanceProblem = { id: string; archetype: 'balance'; title: string; emoji: string; difficultyLabel: 'かんたん' | 'ふつう' | 'やってみる'; prompt: string; notches: number; weights: Weight[]; gramsRange?: { min: number; max: number; step: number }; solved: { discovery: string; formula: string; realWorldTitle: string; realWorldBody: string; note?: string } }
export type LaunchLane = { id: string; label: string; goalCenterCm: number; goalToleranceCm: number }
export type LaunchProblem = { id: string; archetype: 'launch'; title: string; emoji: string; difficultyLabel: 'かんたん' | 'ふつう' | 'やってみる'; grade: 3; subject: 'science'; curriculum: { code: string; unit: string }; prompt: string; courseLengthCm: number; maxStretchCm: number; lanes: LaunchLane[]; solved: { discovery: string; formula: string; realWorldTitle: string; realWorldBody: string; note?: string } }
export type Problem = BalanceProblem | LaunchProblem

const balanceProblems: BalanceProblem[] = [
 { id: 'lever-01', archetype: 'balance', title: 'つりあいを 見つけよう', emoji: '⚖️', difficultyLabel: 'かんたん', prompt: '右のおもりを動かして、てこを水平にしよう。', notches: 6, weights: [{ id: 'left', grams: 10, position: -3, movable: false, gramsEditable: false }, { id: 'right', grams: 10, position: 6, movable: true, gramsEditable: false }], solved: { discovery: 'おなじ おもさなら、してんから おなじ きょり', formula: '10g × 3 = 10g × 3', realWorldTitle: 'シーソー', realWorldBody: 'シーソーも、左右のおもさと してんからの きょりで つりあいが きまるよ。' } },
 { id: 'lever-02', archetype: 'balance', title: 'おもさが ちがうとき', emoji: '🪨', difficultyLabel: 'ふつう', prompt: 'おもい右のおもりを、どこに置くと水平になるかな？', notches: 6, weights: [{ id: 'left', grams: 10, position: -6, movable: false, gramsEditable: false }, { id: 'right', grams: 20, position: 6, movable: true, gramsEditable: false }], solved: { discovery: 'おもい ほうを、してんに ちかづける', formula: '10g × 6 = 20g × 3', realWorldTitle: 'くぎぬき', realWorldBody: 'くぎぬきは、長いほうを持つと、小さな力でも くぎを ぬきやすくなるよ。' } },
 { id: 'lever-03', archetype: 'balance', title: 'こたえは ひとつじゃない', emoji: '🧩', difficultyLabel: 'やってみる', prompt: 'おもさや場所を変えて、水平になる組み合わせを見つけよう。', notches: 6, weights: [{ id: 'left', grams: 15, position: -4, movable: false, gramsEditable: true }, { id: 'right', grams: 5, position: 6, movable: true, gramsEditable: true }], gramsRange: { min: 5, max: 30, step: 5 }, solved: { discovery: 'つりあう やりかたは、ひとつじゃない', formula: '15g × 4 = 20g × 3（れい）', realWorldTitle: 'はかり', realWorldBody: 'はかりは、ものの おもさを くらべるために、てこの つりあいを つかっているよ。' } },
]
const launchProblems: LaunchProblem[] = [
 { id: 'rubber-01', archetype: 'launch', title: 'ゴムの力 ①', emoji: '🚗', difficultyLabel: 'かんたん', grade: 3, subject: 'science', curriculum: { code: '理科 3年 A(2)', unit: '風とゴムの力の働き' }, prompt: '車を うしろに ひっぱって はなそう。ゴールの ところで とめられるかな？', courseLengthCm: 950, maxStretchCm: 15, lanes: [{ id: 'a', label: 'コース', goalCenterCm: 400, goalToleranceCm: 20 }], solved: { discovery: 'ゴムを ながく のばすほど、車は とおくまで すすむ', formula: '10cm のばす → 400cm（4m）すすんだ', realWorldTitle: 'これ、どこで つかわれてる？', realWorldBody: 'パチンコ、ゴム鉄ぽう、ボウガン、それから車のサスペンション。ぜんぶ「もとに もどろうとする力」をつかってる。' } },
 { id: 'rubber-02', archetype: 'launch', title: 'ゴムの力 ②', emoji: '🏁', difficultyLabel: 'ふつう', grade: 3, subject: 'science', curriculum: { code: '理科 3年 A(2)', unit: '風とゴムの力の働き' }, prompt: 'こんどは ゴールが 2つ。ちかい ゴールと とおい ゴール、りょうほう とめてみよう', courseLengthCm: 950, maxStretchCm: 15, lanes: [{ id: 'a', label: 'ちかい ゴール', goalCenterCm: 100, goalToleranceCm: 20 }, { id: 'b', label: 'とおい ゴール', goalCenterCm: 900, goalToleranceCm: 20 }], solved: { discovery: 'ちかい ゴールは みじかく、とおい ゴールは ながく のばす', formula: '5cm のばす → 100cm　／　15cm のばす → 900cm', realWorldTitle: 'これ、どこで つかわれてる？', realWorldBody: 'きょりを ねらって とばす ものは、ぜんぶ この かんがえかた。アーチェリー、水てっぽう、それから しょうぼう車のホース。', note: 'きろくを たてに ならべて 見てみよう。のばした 長さと すすんだ きょりに、きまりが 見えるよ' } },
]
export const problems: Problem[] = [...balanceProblems, ...launchProblems]
export function getProblem(id: string) { return problems.find((p) => p.id === id) }
export function getNextProblem(id: string) { const index = problems.findIndex((p) => p.id === id); return problems[(index + 1) % problems.length] }
export function isLaunchProblem(problem: Problem): problem is LaunchProblem { return problem.archetype === 'launch' }
